using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text.RegularExpressions;

namespace BeavisCli
{
    /// <summary>
    /// Represents a file uploaded from the client-side.
    /// </summary>
    public class FileContent
    {
        /// <summary>
        /// File name
        /// </summary>
        [JsonProperty("name")]
        public string Name { get; set; }

        /// <summary>
        /// File type (MIME type)
        /// </summary>
        [JsonProperty("type")]
        public string Type { get; set; }

        /// <summary>
        /// File data url (https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URIs)
        /// </summary>
        [JsonProperty("dataUrl")]
        public string DataUrl { get; set; }

        /// <summary>
        /// Get file bytes.
        /// </summary>
        /// <returns>files bytes</returns>
        public byte[] GetBytes()
        {
            if (string.IsNullOrEmpty(DataUrl))
            {
                throw new InvalidOperationException($"{nameof(DataUrl)} is null or empty string.");
            }

            const string separator = ";base64,";

            var index = DataUrl.IndexOf(separator, StringComparison.InvariantCulture);
            if (!(index > 0))
            {
                throw new InvalidOperationException($"{nameof(DataUrl)} is weird!!!");
            }

            index = index + separator.Length;
            var base64Data = DataUrl.Substring(index);
            var binData = Convert.FromBase64String(base64Data);
            using (var stream = new MemoryStream(binData))
            {
                byte[] bytes = stream.ToArray();
                return bytes;
            }
        }

        public static string ResolveType(string name)
        {
            string type = null;
            FileInfo fi = new FileInfo(name);
            string extension = fi.Extension;
            if (!string.IsNullOrEmpty(extension))
            {
                Find(extension, delegate (string value) { type = value; });
            }
            return type ?? (type = DefaultType);
        }

        private const string DefaultType = "application/octet-stream";

        private static void Find(string value, Action<string> callback)
        {
            if (string.IsNullOrEmpty(value))
            {
                return;
            }

            void Check(string type, string extension)
            {
                if (value.StartsWith("."))
                {
                    extension = "." + extension;
                }

                if (string.Equals(value, extension, StringComparison.InvariantCultureIgnoreCase))
                {
                    callback(type);
                }
            }

            Check("application/vnd.hzn-3d-crossword", "x3d");
            Check("video/3gpp", "3gp");
            Check("video/3gpp2", "3g2");
            Check("application/vnd.mseq", "mseq");
            Check("application/vnd.3m.post-it-notes", "pwn");
            Check("application/vnd.3gpp.pic-bw-large", "plb");
            Check("application/vnd.3gpp.pic-bw-small", "psb");
            Check("application/vnd.3gpp.pic-bw-var", "pvb");
            Check("application/vnd.3gpp2.tcap", "tcap");
            Check("application/x-7z-compressed", "7z");
            Check("application/x-abiword", "abw");
            Check("application/x-ace-compressed", "ace");
            Check("application/vnd.americandynamics.acc", "acc");
            Check("application/vnd.acucobol", "acu");
            Check("application/vnd.acucorp", "atc");
            Check("audio/adpcm", "adp");
            Check("application/x-authorware-bin", "aab");
            Check("application/x-authorware-map", "aam");
            Check("application/x-authorware-seg", "aas");
            Check("application/vnd.adobe.air-application-installer-package+zip", "air");
            Check("application/x-shockwave-flash", "swf");
            Check("application/vnd.adobe.fxp", "fxp");
            Check("application/pdf", "pdf");
            Check("application/vnd.cups-ppd", "ppd");
            Check("application/x-director", "dir");
            Check("application/vnd.adobe.xdp+xml", "xdp");
            Check("application/vnd.adobe.xfdf", "xfdf");
            Check("audio/x-aac", "aac");
            Check("application/vnd.ahead.space", "ahead");
            Check("application/vnd.airzip.filesecure.azf", "azf");
            Check("application/vnd.airzip.filesecure.azs", "azs");
            Check("application/vnd.amazon.ebook", "azw");
            Check("application/vnd.amiga.ami", "ami");
            Check("application/vnd.android.package-archive", "apk");
            Check("application/vnd.anser-web-certificate-issue-initiation", "cii");
            Check("application/vnd.anser-web-funds-transfer-initiation", "fti");
            Check("application/vnd.antix.game-component", "atx");
            Check("application/x-apple-diskimage", "dmg");
            Check("application/vnd.apple.installer+xml", "mpkg");
            Check("application/applixware", "aw");
            Check("application/vnd.hhe.lesson-player", "les");
            Check("application/vnd.aristanetworks.swi", "swi");
            Check("text/x-asm", "s");
            Check("application/atomcat+xml", "atomcat");
            Check("application/atomsvc+xml", "atomsvc");
            Check("application/atom+xml", "atom, .xml");
            Check("application/pkix-attr-cert", "ac");
            Check("audio/x-aiff", "aif");
            Check("video/x-msvideo", "avi");
            Check("application/vnd.audiograph", "aep");
            Check("image/vnd.dxf", "dxf");
            Check("model/vnd.dwf", "dwf");
            Check("text/plain-bas", "par");
            Check("application/x-bcpio", "bcpio");
            Check("application/octet-stream", "bin");
            Check("image/bmp", "bmp");
            Check("application/x-bittorrent", "torrent");
            Check("application/vnd.rim.cod", "cod");
            Check("application/vnd.blueice.multipass", "mpm");
            Check("application/vnd.bmi", "bmi");
            Check("application/x-sh", "sh");
            Check("image/prs.btif", "btif");
            Check("application/vnd.businessobjects", "rep");
            Check("application/x-bzip", "bz");
            Check("application/x-bzip2", "bz2");
            Check("application/x-csh", "csh");
            Check("text/x-c", "c");
            Check("application/vnd.chemdraw+xml", "cdxml");
            Check("text/css", "css");
            Check("chemical/x-cdx", "cdx");
            Check("chemical/x-cml", "cml");
            Check("chemical/x-csml", "csml");
            Check("application/vnd.contact.cmsg", "cdbcmsg");
            Check("application/vnd.claymore", "cla");
            Check("application/vnd.clonk.c4group", "c4g");
            Check("image/vnd.dvb.subtitle", "sub");
            Check("application/cdmi-capability", "cdmia");
            Check("application/cdmi-container", "cdmic");
            Check("application/cdmi-domain", "cdmid");
            Check("application/cdmi-object", "cdmio");
            Check("application/cdmi-queue", "cdmiq");
            Check("application/vnd.cluetrust.cartomobile-config", "c11amc");
            Check("application/vnd.cluetrust.cartomobile-config-pkg", "c11amz");
            Check("image/x-cmu-raster", "ras");
            Check("model/vnd.collada+xml", "dae");
            Check("text/csv", "csv");
            Check("application/mac-compactpro", "cpt");
            Check("application/vnd.wap.wmlc", "wmlc");
            Check("image/cgm", "cgm");
            Check("x-conference/x-cooltalk", "ice");
            Check("image/x-cmx", "cmx");
            Check("application/vnd.xara", "xar");
            Check("application/vnd.cosmocaller", "cmc");
            Check("application/x-cpio", "cpio");
            Check("application/vnd.crick.clicker", "clkx");
            Check("application/vnd.crick.clicker.keyboard", "clkk");
            Check("application/vnd.crick.clicker.palette", "clkp");
            Check("application/vnd.crick.clicker.template", "clkt");
            Check("application/vnd.crick.clicker.wordbank", "clkw");
            Check("application/vnd.criticaltools.wbs+xml", "wbs");
            Check("application/vnd.rig.cryptonote", "cryptonote");
            Check("chemical/x-cif", "cif");
            Check("chemical/x-cmdf", "cmdf");
            Check("application/cu-seeme", "cu");
            Check("application/prs.cww", "cww");
            Check("text/vnd.curl", "curl");
            Check("text/vnd.curl.dcurl", "dcurl");
            Check("text/vnd.curl.mcurl", "mcurl");
            Check("text/vnd.curl.scurl", "scurl");
            Check("application/vnd.curl.car", "car");
            Check("application/vnd.curl.pcurl", "pcurl");
            Check("application/vnd.yellowriver-custom-menu", "cmp");
            Check("application/dssc+der", "dssc");
            Check("application/dssc+xml", "xdssc");
            Check("application/x-debian-package", "deb");
            Check("audio/vnd.dece.audio", "uva");
            Check("image/vnd.dece.graphic", "uvi");
            Check("video/vnd.dece.hd", "uvh");
            Check("video/vnd.dece.mobile", "uvm");
            Check("video/vnd.uvvu.mp4", "uvu");
            Check("video/vnd.dece.pd", "uvp");
            Check("video/vnd.dece.sd", "uvs");
            Check("video/vnd.dece.video", "uvv");
            Check("application/x-dvi", "dvi");
            Check("application/vnd.fdsn.seed", "seed");
            Check("application/x-dtbook+xml", "dtb");
            Check("application/x-dtbresource+xml", "res");
            Check("application/vnd.dvb.ait", "ait");
            Check("application/vnd.dvb.service", "svc");
            Check("audio/vnd.digital-winds", "eol");
            Check("image/vnd.djvu", "djvu");
            Check("application/xml-dtd", "dtd");
            Check("application/vnd.dolby.mlp", "mlp");
            Check("application/x-doom", "wad");
            Check("application/vnd.dpgraph", "dpg");
            Check("audio/vnd.dra", "dra");
            Check("application/vnd.dreamfactory", "dfac");
            Check("audio/vnd.dts", "dts");
            Check("audio/vnd.dts.hd", "dtshd");
            Check("image/vnd.dwg", "dwg");
            Check("application/vnd.dynageo", "geo");
            Check("application/ecmascript", "es");
            Check("application/vnd.ecowin.chart", "mag");
            Check("image/vnd.fujixerox.edmics-mmr", "mmr");
            Check("image/vnd.fujixerox.edmics-rlc", "rlc");
            Check("application/exi", "exi");
            Check("application/vnd.proteus.magazine", "mgz");
            Check("application/epub+zip", "epub");
            Check("message/rfc822", "eml");
            Check("application/vnd.enliven", "nml");
            Check("application/vnd.is-xpr", "xpr");
            Check("image/vnd.xiff", "xif");
            Check("application/vnd.xfdl", "xfdl");
            Check("application/emma+xml", "emma");
            Check("application/vnd.ezpix-album", "ez2");
            Check("application/vnd.ezpix-package", "ez3");
            Check("image/vnd.fst", "fst");
            Check("video/vnd.fvt", "fvt");
            Check("image/vnd.fastbidsheet", "fbs");
            Check("application/vnd.denovo.fcselayout-link", "fe_launch");
            Check("video/x-f4v", "f4v");
            Check("video/x-flv", "flv");
            Check("image/vnd.fpx", "fpx");
            Check("image/vnd.net-fpx", "npx");
            Check("text/vnd.fmi.flexstor", "flx");
            Check("video/x-fli", "fli");
            Check("application/vnd.fluxtime.clip", "ftc");
            Check("application/vnd.fdf", "fdf");
            Check("text/x-fortran", "f");
            Check("application/vnd.mif", "mif");
            Check("application/vnd.framemaker", "fm");
            Check("image/x-freehand", "fh");
            Check("application/vnd.fsc.weblaunch", "fsc");
            Check("application/vnd.frogans.fnc", "fnc");
            Check("application/vnd.frogans.ltf", "ltf");
            Check("application/vnd.fujixerox.ddd", "ddd");
            Check("application/vnd.fujixerox.docuworks", "xdw");
            Check("application/vnd.fujixerox.docuworks.binder", "xbd");
            Check("application/vnd.fujitsu.oasys", "oas");
            Check("application/vnd.fujitsu.oasys2", "oa2");
            Check("application/vnd.fujitsu.oasys3", "oa3");
            Check("application/vnd.fujitsu.oasysgp", "fg5");
            Check("application/vnd.fujitsu.oasysprs", "bh2");
            Check("application/x-futuresplash", "spl");
            Check("application/vnd.fuzzysheet", "fzs");
            Check("image/g3fax", "g3");
            Check("application/vnd.gmx", "gmx");
            Check("model/vnd.gtw", "gtw");
            Check("application/vnd.genomatix.tuxedo", "txd");
            Check("application/vnd.geogebra.file", "ggb");
            Check("application/vnd.geogebra.tool", "ggt");
            Check("model/vnd.gdl", "gdl");
            Check("application/vnd.geometry-explorer", "gex");
            Check("application/vnd.geonext", "gxt");
            Check("application/vnd.geoplan", "g2w");
            Check("application/vnd.geospace", "g3w");
            Check("application/x-font-ghostscript", "gsf");
            Check("application/x-font-bdf", "bdf");
            Check("application/x-gtar", "gtar");
            Check("application/x-texinfo", "texinfo");
            Check("application/x-gnumeric", "gnumeric");
            Check("application/vnd.google-earth.kml+xml", "kml");
            Check("application/vnd.google-earth.kmz", "kmz");
            Check("application/vnd.grafeq", "gqf");
            Check("image/gif", "gif");
            Check("text/vnd.graphviz", "gv");
            Check("application/vnd.groove-account", "gac");
            Check("application/vnd.groove-help", "ghf");
            Check("application/vnd.groove-identity-message", "gim");
            Check("application/vnd.groove-injector", "grv");
            Check("application/vnd.groove-tool-message", "gtm");
            Check("application/vnd.groove-tool-template", "tpl");
            Check("application/vnd.groove-vcard", "vcg");
            Check("video/h261", "h261");
            Check("video/h263", "h263");
            Check("video/h264", "h264");
            Check("application/vnd.hp-hpid", "hpid");
            Check("application/vnd.hp-hps", "hps");
            Check("application/x-hdf", "hdf");
            Check("audio/vnd.rip", "rip");
            Check("application/vnd.hbci", "hbci");
            Check("application/vnd.hp-jlyt", "jlt");
            Check("application/vnd.hp-pcl", "pcl");
            Check("application/vnd.hp-hpgl", "hpgl");
            Check("application/vnd.yamaha.hv-script", "hvs");
            Check("application/vnd.yamaha.hv-dic", "hvd");
            Check("application/vnd.yamaha.hv-voice", "hvp");
            Check("application/vnd.hydrostatix.sof-data", "sfd-hdstx");
            Check("application/hyperstudio", "stk");
            Check("application/vnd.hal+xml", "hal");
            Check("text/html", "html");
            Check("application/vnd.ibm.rights-management", "irm");
            Check("application/vnd.ibm.secure-container", "sc");
            Check("text/calendar", "ics");
            Check("application/vnd.iccprofile", "icc");
            Check("image/x-icon", "ico");
            Check("application/vnd.igloader", "igl");
            Check("image/ief", "ief");
            Check("application/vnd.immervision-ivp", "ivp");
            Check("application/vnd.immervision-ivu", "ivu");
            Check("application/reginfo+xml", "rif");
            Check("text/vnd.in3d.3dml", "3dml");
            Check("text/vnd.in3d.spot", "spot");
            Check("model/iges", "igs");
            Check("application/vnd.intergeo", "i2g");
            Check("application/vnd.cinderella", "cdy");
            Check("application/vnd.intercon.formnet", "xpw");
            Check("application/vnd.isac.fcs", "fcs");
            Check("application/ipfix", "ipfix");
            Check("application/pkix-cert", "cer");
            Check("application/pkixcmp", "pki");
            Check("application/pkix-crl", "crl");
            Check("application/pkix-pkipath", "pkipath");
            Check("application/vnd.insors.igm", "igm");
            Check("application/vnd.ipunplugged.rcprofile", "rcprofile");
            Check("application/vnd.irepository.package+xml", "irp");
            Check("text/vnd.sun.j2me.app-descriptor", "jad");
            Check("application/java-archive", "jar");
            Check("application/java-vm", "class");
            Check("application/x-java-jnlp-file", "jnlp");
            Check("application/java-serialized-object", "ser");
            Check("text/x-java-source,java", "java");
            Check("application/javascript", "js");
            Check("application/json", "json");
            Check("application/vnd.joost.joda-archive", "joda");
            Check("video/jpm", "jpm");
            Check("image/jpeg", "jpeg");
            Check("image/jpeg", "jpg");
            Check("image/pjpeg", "pjpeg");
            Check("video/jpeg", "jpgv");
            Check("application/vnd.kahootz", "ktz");
            Check("application/vnd.chipnuts.karaoke-mmd", "mmd");
            Check("application/vnd.kde.karbon", "karbon");
            Check("application/vnd.kde.kchart", "chrt");
            Check("application/vnd.kde.kformula", "kfo");
            Check("application/vnd.kde.kivio", "flw");
            Check("application/vnd.kde.kontour", "kon");
            Check("application/vnd.kde.kpresenter", "kpr");
            Check("application/vnd.kde.kspread", "ksp");
            Check("application/vnd.kde.kword", "kwd");
            Check("application/vnd.kenameaapp", "htke");
            Check("application/vnd.kidspiration", "kia");
            Check("application/vnd.kinar", "kne");
            Check("application/vnd.kodak-descriptor", "sse");
            Check("application/vnd.las.las+xml", "lasxml");
            Check("application/x-latex", "latex");
            Check("application/vnd.llamagraphics.life-balance.desktop", "lbd");
            Check("application/vnd.llamagraphics.life-balance.exchange+xml", "lbe");
            Check("application/vnd.jam", "jam");
            Check("application/vnd.lotus-1-2-3", "123");
            Check("application/vnd.lotus-approach", "apr");
            Check("application/vnd.lotus-freelance", "pre");
            Check("application/vnd.lotus-notes", "nsf");
            Check("application/vnd.lotus-organizer", "org");
            Check("application/vnd.lotus-screencam", "scm");
            Check("application/vnd.lotus-wordpro", "lwp");
            Check("audio/vnd.lucent.voice", "lvp");
            Check("audio/x-mpegurl", "m3u");
            Check("video/x-m4v", "m4v");
            Check("application/mac-binhex40", "hqx");
            Check("application/vnd.macports.portpkg", "portpkg");
            Check("application/vnd.osgeo.mapguide.package", "mgp");
            Check("application/marc", "mrc");
            Check("application/marcxml+xml", "mrcx");
            Check("application/mxf", "mxf");
            Check("application/vnd.wolfram.player", "nbp");
            Check("application/mathematica", "ma");
            Check("application/mathml+xml", "mathml");
            Check("application/mbox", "mbox");
            Check("application/vnd.medcalcdata", "mc1");
            Check("application/mediaservercontrol+xml", "mscml");
            Check("application/vnd.mediastation.cdkey", "cdkey");
            Check("application/vnd.mfer", "mwf");
            Check("application/vnd.mfmp", "mfm");
            Check("model/mesh", "msh");
            Check("application/mads+xml", "mads");
            Check("application/mets+xml", "mets");
            Check("application/mods+xml", "mods");
            Check("application/metalink4+xml", "meta4");
            Check("application/vnd.mcd", "mcd");
            Check("application/vnd.micrografx.flo", "flo");
            Check("application/vnd.micrografx.igx", "igx");
            Check("application/vnd.eszigno3+xml", "es3");
            Check("application/x-msaccess", "mdb");
            Check("video/x-ms-asf", "asf");
            Check("application/x-msdownload", "exe");
            Check("application/vnd.ms-artgalry", "cil");
            Check("application/vnd.ms-cab-compressed", "cab");
            Check("application/vnd.ms-ims", "ims");
            Check("application/x-ms-application", "application");
            Check("application/x-msclip", "clp");
            Check("image/vnd.ms-modi", "mdi");
            Check("application/vnd.ms-fontobject", "eot");
            Check("application/vnd.ms-excel", "xls");
            Check("application/vnd.ms-excel.addin.macroenabled.12", "xlam");
            Check("application/vnd.ms-excel.sheet.binary.macroenabled.12", "xlsb");
            Check("application/vnd.ms-excel.template.macroenabled.12", "xltm");
            Check("application/vnd.ms-excel.sheet.macroenabled.12", "xlsm");
            Check("application/vnd.ms-htmlhelp", "chm");
            Check("application/x-mscardfile", "crd");
            Check("application/vnd.ms-lrm", "lrm");
            Check("application/x-msmediaview", "mvb");
            Check("application/x-msmoney", "mny");
            Check("application/vnd.openxmlformats-officedocument.presentationml.presentation", "pptx");
            Check("application/vnd.openxmlformats-officedocument.presentationml.slide", "sldx");
            Check("application/vnd.openxmlformats-officedocument.presentationml.slideshow", "ppsx");
            Check("application/vnd.openxmlformats-officedocument.presentationml.template", "potx");
            Check("application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "xlsx");
            Check("application/vnd.openxmlformats-officedocument.spreadsheetml.template", "xltx");
            Check("application/vnd.openxmlformats-officedocument.wordprocessingml.document", "docx");
            Check("application/vnd.openxmlformats-officedocument.wordprocessingml.template", "dotx");
            Check("application/x-msbinder", "obd");
            Check("application/vnd.ms-officetheme", "thmx");
            Check("application/onenote", "onetoc");
            Check("audio/vnd.ms-playready.media.pya", "pya");
            Check("video/vnd.ms-playready.media.pyv", "pyv");
            Check("application/vnd.ms-powerpoint", "ppt");
            Check("application/vnd.ms-powerpoint.addin.macroenabled.12", "ppam");
            Check("application/vnd.ms-powerpoint.slide.macroenabled.12", "sldm");
            Check("application/vnd.ms-powerpoint.presentation.macroenabled.12", "pptm");
            Check("application/vnd.ms-powerpoint.slideshow.macroenabled.12", "ppsm");
            Check("application/vnd.ms-powerpoint.template.macroenabled.12", "potm");
            Check("application/vnd.ms-project", "mpp");
            Check("application/x-mspublisher", "pub");
            Check("application/x-msschedule", "scd");
            Check("application/x-silverlight-app", "xap");
            Check("application/vnd.ms-pki.stl", "stl");
            Check("application/vnd.ms-pki.seccat", "cat");
            Check("application/vnd.visio", "vsd");
            Check("application/vnd.visio2013", "vsdx");
            Check("video/x-ms-wm", "wm");
            Check("audio/x-ms-wma", "wma");
            Check("audio/x-ms-wax", "wax");
            Check("video/x-ms-wmx", "wmx");
            Check("application/x-ms-wmd", "wmd");
            Check("application/vnd.ms-wpl", "wpl");
            Check("application/x-ms-wmz", "wmz");
            Check("video/x-ms-wmv", "wmv");
            Check("video/x-ms-wvx", "wvx");
            Check("application/x-msmetafile", "wmf");
            Check("application/x-msterminal", "trm");
            Check("application/msword", "doc");
            Check("application/vnd.ms-word.document.macroenabled.12", "docm");
            Check("application/vnd.ms-word.template.macroenabled.12", "dotm");
            Check("application/x-mswrite", "wri");
            Check("application/vnd.ms-works", "wps");
            Check("application/x-ms-xbap", "xbap");
            Check("application/vnd.ms-xpsdocument", "xps");
            Check("audio/midi", "mid");
            Check("application/vnd.ibm.minipay", "mpy");
            Check("application/vnd.ibm.modcap", "afp");
            Check("application/vnd.jcp.javame.midlet-rms", "rms");
            Check("application/vnd.tmobile-livetv", "tmo");
            Check("application/x-mobipocket-ebook", "prc");
            Check("application/vnd.mobius.mbk", "mbk");
            Check("application/vnd.mobius.dis", "dis");
            Check("application/vnd.mobius.plc", "plc");
            Check("application/vnd.mobius.mqy", "mqy");
            Check("application/vnd.mobius.msl", "msl");
            Check("application/vnd.mobius.txf", "txf");
            Check("application/vnd.mobius.daf", "daf");
            Check("text/vnd.fly", "fly");
            Check("application/vnd.mophun.certificate", "mpc");
            Check("application/vnd.mophun.application", "mpn");
            Check("video/mj2", "mj2");
            Check("audio/mpeg", "mpga");
            Check("video/vnd.mpegurl", "mxu");
            Check("video/mpeg", "mpeg");
            Check("application/mp21", "m21");
            Check("audio/mp4", "mp4a");
            Check("video/mp4", "mp4");
            Check("application/vnd.apple.mpegurl", "m3u8");
            Check("application/vnd.musician", "mus");
            Check("application/vnd.muvee.style", "msty");
            Check("application/xv+xml", "mxml");
            Check("application/vnd.nokia.n-gage.data", "ngdat");
            Check("application/vnd.nokia.n-gage.symbian.install", "n-gage");
            Check("application/x-dtbncx+xml", "ncx");
            Check("application/x-netcdf", "nc");
            Check("application/vnd.neurolanguage.nlu", "nlu");
            Check("application/vnd.dna", "dna");
            Check("application/vnd.noblenet-directory", "nnd");
            Check("application/vnd.noblenet-sealer", "nns");
            Check("application/vnd.noblenet-web", "nnw");
            Check("application/vnd.nokia.radio-preset", "rpst");
            Check("application/vnd.nokia.radio-presets", "rpss");
            Check("text/n3", "n3");
            Check("application/vnd.novadigm.edm", "edm");
            Check("application/vnd.novadigm.edx", "edx");
            Check("application/vnd.novadigm.ext", "ext");
            Check("application/vnd.flographit", "gph");
            Check("audio/vnd.nuera.ecelp4800", "ecelp4800");
            Check("audio/vnd.nuera.ecelp7470", "ecelp7470");
            Check("audio/vnd.nuera.ecelp9600", "ecelp9600");
            Check("application/oda", "oda");
            Check("application/ogg", "ogx");
            Check("audio/ogg", "oga");
            Check("video/ogg", "ogv");
            Check("application/vnd.oma.dd2+xml", "dd2");
            Check("application/vnd.oasis.opendocument.text-web", "oth");
            Check("application/oebps-package+xml", "opf");
            Check("application/vnd.intu.qbo", "qbo");
            Check("application/vnd.openofficeorg.extension", "oxt");
            Check("application/vnd.yamaha.openscoreformat", "osf");
            Check("audio/webm", "weba");
            Check("video/webm", "webm");
            Check("application/vnd.oasis.opendocument.chart", "odc");
            Check("application/vnd.oasis.opendocument.chart-template", "otc");
            Check("application/vnd.oasis.opendocument.database", "odb");
            Check("application/vnd.oasis.opendocument.formula", "odf");
            Check("application/vnd.oasis.opendocument.formula-template", "odft");
            Check("application/vnd.oasis.opendocument.graphics", "odg");
            Check("application/vnd.oasis.opendocument.graphics-template", "otg");
            Check("application/vnd.oasis.opendocument.image", "odi");
            Check("application/vnd.oasis.opendocument.image-template", "oti");
            Check("application/vnd.oasis.opendocument.presentation", "odp");
            Check("application/vnd.oasis.opendocument.presentation-template", "otp");
            Check("application/vnd.oasis.opendocument.spreadsheet", "ods");
            Check("application/vnd.oasis.opendocument.spreadsheet-template", "ots");
            Check("application/vnd.oasis.opendocument.text", "odt");
            Check("application/vnd.oasis.opendocument.text-master", "odm");
            Check("application/vnd.oasis.opendocument.text-template", "ott");
            Check("image/ktx", "ktx");
            Check("application/vnd.sun.xml.calc", "sxc");
            Check("application/vnd.sun.xml.calc.template", "stc");
            Check("application/vnd.sun.xml.draw", "sxd");
            Check("application/vnd.sun.xml.draw.template", "std");
            Check("application/vnd.sun.xml.impress", "sxi");
            Check("application/vnd.sun.xml.impress.template", "sti");
            Check("application/vnd.sun.xml.math", "sxm");
            Check("application/vnd.sun.xml.writer", "sxw");
            Check("application/vnd.sun.xml.writer.global", "sxg");
            Check("application/vnd.sun.xml.writer.template", "stw");
            Check("application/x-font-otf", "otf");
            Check("application/vnd.yamaha.openscoreformat.osfpvg+xml", "osfpvg");
            Check("application/vnd.osgi.dp", "dp");
            Check("application/vnd.palm", "pdb");
            Check("text/x-pascal", "p");
            Check("application/vnd.pawaafile", "paw");
            Check("application/vnd.hp-pclxl", "pclxl");
            Check("application/vnd.picsel", "efif");
            Check("image/x-pcx", "pcx");
            Check("image/vnd.adobe.photoshop", "psd");
            Check("application/pics-rules", "prf");
            Check("image/x-pict", "pic");
            Check("application/x-chat", "chat");
            Check("application/pkcs10", "p10");
            Check("application/x-pkcs12", "p12");
            Check("application/pkcs7-mime", "p7m");
            Check("application/pkcs7-signature", "p7s");
            Check("application/x-pkcs7-certreqresp", "p7r");
            Check("application/x-pkcs7-certificates", "p7b");
            Check("application/pkcs8", "p8");
            Check("application/vnd.pocketlearn", "plf");
            Check("image/x-portable-anymap", "pnm");
            Check("image/x-portable-bitmap", "pbm");
            Check("application/x-font-pcf", "pcf");
            Check("application/font-tdpfr", "pfr");
            Check("application/x-chess-pgn", "pgn");
            Check("image/x-portable-graymap", "pgm");
            Check("image/png", "png");
            Check("image/x-portable-pixmap", "ppm");
            Check("application/pskc+xml", "pskcxml");
            Check("application/vnd.ctc-posml", "pml");
            Check("application/postscript", "ai");
            Check("application/x-font-type1", "pfa");
            Check("application/vnd.powerbuilder6", "pbd");
            Check("application/pgp-encrypted", "pgp");
            Check("application/vnd.previewsystems.box", "box");
            Check("application/vnd.pvi.ptid1", "ptid");
            Check("application/pls+xml", "pls");
            Check("application/vnd.pg.format", "str");
            Check("application/vnd.pg.osasli", "ei6");
            Check("text/prs.lines.tag", "dsc");
            Check("application/x-font-linux-psf", "psf");
            Check("application/vnd.publishare-delta-tree", "qps");
            Check("application/vnd.pmi.widget", "wg");
            Check("application/vnd.quark.quarkxpress", "qxd");
            Check("application/vnd.epson.esf", "esf");
            Check("application/vnd.epson.msf", "msf");
            Check("application/vnd.epson.ssf", "ssf");
            Check("application/vnd.epson.quickanime", "qam");
            Check("application/vnd.intu.qfx", "qfx");
            Check("video/quicktime", "qt");
            Check("application/x-rar-compressed", "rar");
            Check("audio/x-pn-realaudio", "ram");
            Check("audio/x-pn-realaudio-plugin", "rmp");
            Check("application/rsd+xml", "rsd");
            Check("application/vnd.rn-realmedia", "rm");
            Check("application/vnd.realvnc.bed", "bed");
            Check("application/vnd.recordare.musicxml", "mxl");
            Check("application/vnd.recordare.musicxml+xml", "musicxml");
            Check("application/relax-ng-compact-syntax", "rnc");
            Check("application/vnd.data-vision.rdz", "rdz");
            Check("application/rdf+xml", "rdf");
            Check("application/vnd.cloanto.rp9", "rp9");
            Check("application/vnd.jisp", "jisp");
            Check("application/rtf", "rtf");
            Check("text/richtext", "rtx");
            Check("application/vnd.route66.link66+xml", "link66");
            Check("application/rss+xml", "rss, .xml");
            Check("application/shf+xml", "shf");
            Check("application/vnd.sailingtracker.track", "st");
            Check("image/svg+xml", "svg");
            Check("application/vnd.sus-calendar", "sus");
            Check("application/sru+xml", "sru");
            Check("application/set-payment-initiation", "setpay");
            Check("application/set-registration-initiation", "setreg");
            Check("application/vnd.sema", "sema");
            Check("application/vnd.semd", "semd");
            Check("application/vnd.semf", "semf");
            Check("application/vnd.seemail", "see");
            Check("application/x-font-snf", "snf");
            Check("application/scvp-vp-request", "spq");
            Check("application/scvp-vp-response", "spp");
            Check("application/scvp-cv-request", "scq");
            Check("application/scvp-cv-response", "scs");
            Check("application/sdp", "sdp");
            Check("text/x-setext", "etx");
            Check("video/x-sgi-movie", "movie");
            Check("application/vnd.shana.informed.formdata", "ifm");
            Check("application/vnd.shana.informed.formtemplate", "itp");
            Check("application/vnd.shana.informed.interchange", "iif");
            Check("application/vnd.shana.informed.package", "ipk");
            Check("application/thraud+xml", "tfi");
            Check("application/x-shar", "shar");
            Check("image/x-rgb", "rgb");
            Check("application/vnd.epson.salt", "slt");
            Check("application/vnd.accpac.simply.aso", "aso");
            Check("application/vnd.accpac.simply.imp", "imp");
            Check("application/vnd.simtech-mindmapper", "twd");
            Check("application/vnd.commonspace", "csp");
            Check("application/vnd.yamaha.smaf-audio", "saf");
            Check("application/vnd.smaf", "mmf");
            Check("application/vnd.yamaha.smaf-phrase", "spf");
            Check("application/vnd.smart.teacher", "teacher");
            Check("application/vnd.svd", "svd");
            Check("application/sparql-query", "rq");
            Check("application/sparql-results+xml", "srx");
            Check("application/srgs", "gram");
            Check("application/srgs+xml", "grxml");
            Check("application/ssml+xml", "ssml");
            Check("application/vnd.koan", "skp");
            Check("text/sgml", "sgml");
            Check("application/vnd.stardivision.calc", "sdc");
            Check("application/vnd.stardivision.draw", "sda");
            Check("application/vnd.stardivision.impress", "sdd");
            Check("application/vnd.stardivision.math", "smf");
            Check("application/vnd.stardivision.writer", "sdw");
            Check("application/vnd.stardivision.writer-global", "sgl");
            Check("application/vnd.stepmania.stepchart", "sm");
            Check("application/x-stuffit", "sit");
            Check("application/x-stuffitx", "sitx");
            Check("application/vnd.solent.sdkm+xml", "sdkm");
            Check("application/vnd.olpc-sugar", "xo");
            Check("audio/basic", "au");
            Check("application/vnd.wqd", "wqd");
            Check("application/vnd.symbian.install", "sis");
            Check("application/smil+xml", "smi");
            Check("application/vnd.syncml+xml", "xsm");
            Check("application/vnd.syncml.dm+wbxml", "bdm");
            Check("application/vnd.syncml.dm+xml", "xdm");
            Check("application/x-sv4cpio", "sv4cpio");
            Check("application/x-sv4crc", "sv4crc");
            Check("application/sbml+xml", "sbml");
            Check("text/tab-separated-values", "tsv");
            Check("image/tiff", "tiff");
            Check("application/vnd.tao.intent-module-archive", "tao");
            Check("application/x-tar", "tar");
            Check("application/x-tcl", "tcl");
            Check("application/x-tex", "tex");
            Check("application/x-tex-tfm", "tfm");
            Check("application/tei+xml", "tei");
            Check("text/plain", "txt");
            Check("application/vnd.spotfire.dxp", "dxp");
            Check("application/vnd.spotfire.sfs", "sfs");
            Check("application/timestamped-data", "tsd");
            Check("application/vnd.trid.tpt", "tpt");
            Check("application/vnd.triscape.mxs", "mxs");
            Check("text/troff", "t");
            Check("application/vnd.trueapp", "tra");
            Check("application/x-font-ttf", "ttf");
            Check("text/turtle", "ttl");
            Check("application/vnd.umajin", "umj");
            Check("application/vnd.uoml+xml", "uoml");
            Check("application/vnd.unity", "unityweb");
            Check("application/vnd.ufdl", "ufd");
            Check("text/uri-list", "uri");
            Check("application/vnd.uiq.theme", "utz");
            Check("application/x-ustar", "ustar");
            Check("text/x-uuencode", "uu");
            Check("text/x-vcalendar", "vcs");
            Check("text/x-vcard", "vcf");
            Check("application/x-cdlink", "vcd");
            Check("application/vnd.vsf", "vsf");
            Check("model/vrml", "wrl");
            Check("application/vnd.vcx", "vcx");
            Check("model/vnd.mts", "mts");
            Check("model/vnd.vtu", "vtu");
            Check("application/vnd.visionary", "vis");
            Check("video/vnd.vivo", "viv");
            Check("application/ccxml+xml,", "ccxml");
            Check("application/voicexml+xml", "vxml");
            Check("application/x-wais-source", "src");
            Check("application/vnd.wap.wbxml", "wbxml");
            Check("image/vnd.wap.wbmp", "wbmp");
            Check("audio/x-wav", "wav");
            Check("application/davmount+xml", "davmount");
            Check("font/woff", "woff");
            Check("font/woff2", "woff2");
            Check("application/wspolicy+xml", "wspolicy");
            Check("image/webp", "webp");
            Check("application/vnd.webturbo", "wtb");
            Check("application/widget", "wgt");
            Check("application/winhlp", "hlp");
            Check("text/vnd.wap.wml", "wml");
            Check("text/vnd.wap.wmlscript", "wmls");
            Check("application/vnd.wap.wmlscriptc", "wmlsc");
            Check("application/vnd.wordperfect", "wpd");
            Check("application/vnd.wt.stf", "stf");
            Check("application/wsdl+xml", "wsdl");
            Check("image/x-xbitmap", "xbm");
            Check("image/x-xpixmap", "xpm");
            Check("image/x-xwindowdump", "xwd");
            Check("application/x-x509-ca-cert", "der");
            Check("application/x-xfig", "fig");
            Check("application/xhtml+xml", "xhtml");
            Check("application/xml", "xml");
            Check("application/xcap-diff+xml", "xdf");
            Check("application/xenc+xml", "xenc");
            Check("application/patch-ops-error+xml", "xer");
            Check("application/resource-lists+xml", "rl");
            Check("application/rls-services+xml", "rs");
            Check("application/resource-lists-diff+xml", "rld");
            Check("application/xslt+xml", "xslt");
            Check("application/xop+xml", "xop");
            Check("application/x-xpinstall", "xpi");
            Check("application/xspf+xml", "xspf");
            Check("application/vnd.mozilla.xul+xml", "xul");
            Check("chemical/x-xyz", "xyz");
            Check("text/yaml", "yaml");
            Check("application/yang", "yang");
            Check("application/yin+xml", "yin");
            Check("application/vnd.zul", "zir");
            Check("application/zip", "zip");
            Check("application/vnd.handheld-entertainment+xml", "zmm");
            Check("application/vnd.zzazz.deck+xml", "zaz");
        }
    }
}
